services:
    database:
        image: postgres:16.3-alpine3.19
        ports:
          - 5432:5432
        environment:
          POSTGRES_DB: TrelloDatabase
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
        healthcheck:
          test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
          interval: 1s
          timeout: 2s
          retries: 10